---
- import_tasks: setup.yml
- import_tasks: nginx.yml
  when: web_server == 'nginx'
- import_tasks: apache2.yml
  when: web_server == 'apache2'
- import_tasks: certificates.yml

- name: Install cronjob for key generation
  cron:
    cron_file: letsencrypt-certificate-renewal
    name: letsencrypt certificate renewal
    user: root
    job: cd {{ acme_tiny_data_directory }} && ./renew-certs.py && /usr/sbin/service nginx reload
    day: "{{ letsencrypt_cronjob_daysofmonth }}"
    hour: 4
    minute: 30
    state: present
